---
# tasks file for httpd
- yum: name=httpd state=present
- service: name=httpd state=restarted enabled=yes
#- name: 'copy configuration file'
- template:
    src: httpd.conf.j2 
    dest: /etc/httpd/conf/httpd.conf
#    remote_src: true
    become: true
#  become_user: root
